export const weatherImages = {
  "partly cloudy": require("./images/partlycloudy.png"),
  "moderate rain": require("./images/moderaterain.png"),
  "patchy rain possible": require("./images/moderaterain.png"),
  sunny: require("./images/icons/sun.png"),
  clear: require("./images/sun.png"),
  'clear sky': require("./images/icons/sun.png"),
  overcast: require("./images/cloud.png"),
  "broken clouds": require("./images/cloud.png"),
  "scattered clouds": require("./images/cloud.png"),
  cloudy: require("./images/cloud.png"),
  "light rain": require("./images/moderaterain.png"),
  "moderate rain at times": require("./images/moderaterain.png"),
  "heavy rain": require("./images/heavyrain.png"),
  "heavy rain at times": require("./images/heavyrain.png"),
  "moderate or heavy freezing rain": require("./images/heavyrain.png"),
  "moderate or heavy rain shower": require("./images/heavyrain.png"),
  "moderate or heavy rain with thunder": require("./images/heavyrain.png"),
  mist: require("./images/mist.png"),
  smoke: require("./images/mist.png"),
  other: require("./images/moderaterain.png"),
};
